-- https://medium.com/@abdelaz9z/best-practices-for-database-design-incorporating-timestamps-and-user-metadata-in-tables-2310527dd677

CREATE TABLE IF NOT EXISTS USERS (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(64) NOT NULL UNIQUE,
    password    VARCHAR(256) NOT NULL,
    enabled     INT NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORITIES (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(64) NOT NULL,
    authority   VARCHAR(64) NOT NULL,
    FOREIGN KEY (username) REFERENCES USERS(username)
);

CREATE TABLE IF NOT EXISTS USERDATA (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR(64) NOT NULL,
    firstName   VARCHAR(64) NOT NULL,
    lastName    VARCHAR(64) NOT NULL,
    email       VARCHAR(256) NOT NULL,
    birthDate   DATE NOT NULL,
    signupDate  DATE NOT NULL,
    FOREIGN KEY (username) REFERENCES USERS(username)
);

CREATE TABLE IF NOT EXISTS COMPLETED_TRAININGS (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(64) NOT NULL,
    trainingId   BIGINT      NOT NULL,
    trainingDate TIMESTAMP   NOT NULL, -- TODO: change to created_at
    FOREIGN KEY (username) REFERENCES USERS (username)
);

CREATE TABLE IF NOT EXISTS PROGRAMMICUSTOM(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- user_id BIGINT NOT NULL,
    username VARCHAR(64) NOT NULL,
    nome varchar(32) NOT NULL,
    kcal double NOT NULL,

    FOREIGN KEY (username) REFERENCES USERS (username)
);

CREATE TABLE IF NOT EXISTS ESERCIZI(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_esercizio varchar(32) NOT NULL,
    numero_serie int NOT NULL,
    numero_ripetizioni int NOT NULL,
    programmaType BIGINT NOT NULL,
    FOREIGN KEY (programmaType) REFERENCES PROGRAMMICUSTOM (id)
);

CREATE TABLE IF NOT EXISTS REVIEWS (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    content VARCHAR(512) NOT NULL,
    created_at TIMESTAMP NOT NULL
);
