spring.application.name=ProgrammiRest-like

spring.datasource.url=jdbc:h2:../databases/RestLike-DB;AUTO_SERVER=TRUE
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.h2.Driver
spring.sql.init.mode=always

server.port=8081