
CREATE TABLE IF NOT EXISTS Programmi(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(32) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS Esercizi(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(32) UNIQUE NOT NULL,
    unit double NOT NULL
);

CREATE TABLE IF NOT EXISTS Composizioni(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_esercizio varchar(32) NOT NULL,
    numero_serie int NOT NULL,
    numero_ripetizioni int NOT NULL,

    programmaType varchar(32) NOT NULL,
    esercizioType varchar(32) NOT NULL,

    FOREIGN KEY (esercizioType) REFERENCES Esercizi (nome),
    FOREIGN KEY (programmaType) REFERENCES Programmi (nome)

);

